import os
import json

# 1. Update fabric.mod.json
fabric_json = "fabric/src/main/resources/fabric.mod.json"
if os.path.exists(fabric_json):
    with open(fabric_json, "r", encoding="utf-8") as f:
        data = f.read()
    data = data.replace('"name": "Dynamic BGM"', '"name": "LuminaBox"')
    data = data.replace('"description": "A custom BGM mod"', '"description": "Streaming Sound Box / 流光音匣"')
    with open(fabric_json, "w", encoding="utf-8") as f:
        f.write(data)

# 2. Update neoforge.mods.toml
neo_toml = "neoforge/src/main/resources/META-INF/neoforge.mods.toml"
if os.path.exists(neo_toml):
    with open(neo_toml, "r", encoding="utf-8") as f:
        data = f.read()
    data = data.replace('displayName="Dynamic BGM"', 'displayName="LuminaBox"')
    data = data.replace('description="''A custom BGM mod''"', 'description="''Streaming Sound Box / 流光音匣''"')
    with open(neo_toml, "w", encoding="utf-8") as f:
        f.write(data)

# 3. Modify MusicPlayerScreen.java
screen_file = "common/src/main/java/com/dynamicbgm/client/gui/MusicPlayerScreen.java"
if os.path.exists(screen_file):
    with open(screen_file, "r", encoding="utf-8") as f:
        code = f.read()
    
    code = code.replace('Component.literal("网络播放模式")', 'Component.translatable("gui.dynamic_bgm.platform.online_mode")')
    code = code.replace('Component.literal("无搜索结果。")', 'Component.translatable("gui.dynamic_bgm.platform.no_results")')
    code = code.replace('Component.literal("网络播放列表为空，请在上方搜索并添加歌曲")', 'Component.translatable("gui.dynamic_bgm.platform.empty_list")')
    code = code.replace('Component.literal("服务器播放列表为空")', 'Component.translatable("gui.dynamic_bgm.server.empty_list")')
    code = code.replace('CustomMusicManager.showToast("已添加到网络播放列表!");', 'CustomMusicManager.showToast(net.minecraft.client.resources.language.I18n.get("gui.dynamic_bgm.toast.added_to_online"));')
    code = code.replace('Component.literal("Audio Debug Log: ")', 'Component.translatable("gui.dynamic_bgm.settings.debug_log")')
    
    with open(screen_file, "w", encoding="utf-8") as f:
        f.write(code)

# 4. Modify CustomMusicManager.java
mgr_file = "common/src/main/java/com/dynamicbgm/audio/CustomMusicManager.java"
if os.path.exists(mgr_file):
    with open(mgr_file, "r", encoding="utf-8") as f:
        code = f.read()
    
    code = code.replace('"检测到安卓系统, 请将音乐文件放入: "', 'net.minecraft.client.resources.language.I18n.get("gui.dynamic_bgm.toast.android_path")')
    code = code.replace('"上传完成!"', 'net.minecraft.client.resources.language.I18n.get("gui.dynamic_bgm.toast.upload_success")')
    code = code.replace('"文件不存在!"', 'net.minecraft.client.resources.language.I18n.get("gui.dynamic_bgm.toast.file_not_found")')
    code = code.replace('"网络请求失败..."', 'net.minecraft.client.resources.language.I18n.get("gui.dynamic_bgm.toast.network_error")')
    
    with open(mgr_file, "w", encoding="utf-8") as f:
        f.write(code)

# 5. Generate Language files
lang_dir = "common/src/main/resources/assets/dynamic_bgm/lang"
os.makedirs(lang_dir, exist_ok=True)

langs_data = {
    "en_us": {
        "key.dynamic_bgm.open_menu": "Open LuminaBox Menu",
        "key.categories.dynamic_bgm.main": "LuminaBox",
        "gui.dynamic_bgm.title": "LuminaBox Controller",
        "gui.dynamic_bgm.tab.local": "Local Music",
        "gui.dynamic_bgm.tab.server": "Server Music",
        "gui.dynamic_bgm.tab.platform": "Platform Music",
        "gui.dynamic_bgm.tab.rules": "Ambient Rules",
        "gui.dynamic_bgm.tab.settings": "Settings",
        "gui.dynamic_bgm.local.title": "Local Music Library",
        "gui.dynamic_bgm.local.no_music": "No local music found.",
        "gui.dynamic_bgm.local.instructions": "Place audio files (.mp3/.ogg) in:",
        "gui.dynamic_bgm.local.open_folder": "Open Folder",
        "gui.dynamic_bgm.local.import": "Import Music",
        "gui.dynamic_bgm.local.download_sample": "Download Sample",
        "gui.dynamic_bgm.local.refresh": "Refresh List",
        "gui.dynamic_bgm.local.status": "Status: ",
        "gui.dynamic_bgm.local.status.ready": "Ready",
        "gui.dynamic_bgm.local.status.downloading": "Downloading sample...",
        "gui.dynamic_bgm.local.status.success": "Download success!",
        "gui.dynamic_bgm.local.status.fail": "Download failed!",
        "gui.dynamic_bgm.server.title": "Server Synced Music",
        "gui.dynamic_bgm.server.status_connected": "Status: Connected to Server",
        "gui.dynamic_bgm.server.priority": "Server playlist takes priority.",
        "gui.dynamic_bgm.server.download_all": "Download All",
        "gui.dynamic_bgm.server.sync": "Sync List",
        "gui.dynamic_bgm.platform.title": "Online Platform Stream",
        "gui.dynamic_bgm.platform.search_placeholder": "Search online music...",
        "gui.dynamic_bgm.platform.search_btn": "Search",
        "gui.dynamic_bgm.platform.login": "Scan QR Login",
        "gui.dynamic_bgm.platform.logout": "Logout",
        "gui.dynamic_bgm.platform.logged_in": "Logged in: ",
        "gui.dynamic_bgm.platform.not_logged_in": "Not logged in",
        "gui.dynamic_bgm.platform.status.waiting": "Waiting for scan...",
        "gui.dynamic_bgm.platform.status.authorizing": "Scanned! Authorizing...",
        "gui.dynamic_bgm.platform.status.success": "Login success!",
        "gui.dynamic_bgm.platform.status.expired": "QR Code expired!",
        "gui.dynamic_bgm.platform.status.error": "Login error: ",
        "gui.dynamic_bgm.rules.title": "Ambient Music Rules",
        "gui.dynamic_bgm.rules.overworld": "Overworld: ",
        "gui.dynamic_bgm.rules.nether": "Nether: ",
        "gui.dynamic_bgm.rules.combat": "Combat: ",
        "gui.dynamic_bgm.rules.boss": "Boss: ",
        "gui.dynamic_bgm.rules.hint": "Tip: Click music name to cycle through local tracks.",
        "gui.dynamic_bgm.settings.title": "Mod Configurations",
        "gui.dynamic_bgm.settings.replace_vanilla": "Replace Vanilla Music: ",
        "gui.dynamic_bgm.settings.replace_desc1": "Overrides vanilla background music",
        "gui.dynamic_bgm.settings.replace_desc2": "when custom music is playing.",
        "gui.dynamic_bgm.player.no_track": "No music playing",
        "gui.dynamic_bgm.player.volume": "Vol",
        "gui.dynamic_bgm.player.play": "Play",
        "gui.dynamic_bgm.player.pause": "Pause",
        "gui.dynamic_bgm.generic.on": "ON",
        "gui.dynamic_bgm.generic.off": "OFF",
        "gui.dynamic_bgm.pause_menu_btn": "LuminaBox",
        "gui.dynamic_bgm.local.select_all": "Select All",
        "gui.dynamic_bgm.local.delete": "Delete",
        "gui.dynamic_bgm.local.pin": "Pin to Top",
        "gui.dynamic_bgm.local.select": "Select",
        "gui.dynamic_bgm.local.cancel": "Cancel",
        "gui.dynamic_bgm.platform.online_mode": "Online Mode",
        "gui.dynamic_bgm.platform.no_results": "No results found.",
        "gui.dynamic_bgm.platform.empty_list": "Online playlist empty. Search to add songs.",
        "gui.dynamic_bgm.server.empty_list": "Server playlist is empty.",
        "gui.dynamic_bgm.toast.added_to_online": "Added to online playlist!",
        "gui.dynamic_bgm.toast.android_path": "Android detected, place music in: ",
        "gui.dynamic_bgm.toast.upload_success": "Upload complete!",
        "gui.dynamic_bgm.toast.file_not_found": "File not found!",
        "gui.dynamic_bgm.toast.network_error": "Network request failed...",
        "gui.dynamic_bgm.settings.debug_log": "Audio Debug Log: "
    },
    "zh_cn": {
        "key.dynamic_bgm.open_menu": "打开音匣菜单",
        "key.categories.dynamic_bgm.main": "流光音匣",
        "gui.dynamic_bgm.title": "流光音匣 控制面板",
        "gui.dynamic_bgm.tab.local": "本地音乐",
        "gui.dynamic_bgm.tab.server": "服务器内置",
        "gui.dynamic_bgm.tab.platform": "网络平台",
        "gui.dynamic_bgm.tab.rules": "环境触发",
        "gui.dynamic_bgm.tab.settings": "模组设置",
        "gui.dynamic_bgm.local.title": "本地音乐库",
        "gui.dynamic_bgm.local.no_music": "未找到本地音乐。",
        "gui.dynamic_bgm.local.instructions": "请将音频文件 (.mp3/.ogg) 放入：",
        "gui.dynamic_bgm.local.open_folder": "打开文件夹",
        "gui.dynamic_bgm.local.import": "导入音乐",
        "gui.dynamic_bgm.local.download_sample": "下载示例",
        "gui.dynamic_bgm.local.refresh": "刷新列表",
        "gui.dynamic_bgm.local.status": "状态：",
        "gui.dynamic_bgm.local.status.ready": "就绪",
        "gui.dynamic_bgm.local.status.downloading": "正在下载示例音乐...",
        "gui.dynamic_bgm.local.status.success": "下载成功！",
        "gui.dynamic_bgm.local.status.fail": "下载失败！",
        "gui.dynamic_bgm.server.title": "服务器内置音乐",
        "gui.dynamic_bgm.server.status_connected": "状态：已连接到服务器",
        "gui.dynamic_bgm.server.priority": "服务器播放列表优先控制。",
        "gui.dynamic_bgm.server.download_all": "下载全部",
        "gui.dynamic_bgm.server.sync": "同步曲库",
        "gui.dynamic_bgm.platform.title": "网络平台播放",
        "gui.dynamic_bgm.platform.search_placeholder": "搜索在线音乐...",
        "gui.dynamic_bgm.platform.search_btn": "搜索",
        "gui.dynamic_bgm.platform.login": "扫码登录",
        "gui.dynamic_bgm.platform.logout": "退出登录",
        "gui.dynamic_bgm.platform.logged_in": "已登录：",
        "gui.dynamic_bgm.platform.not_logged_in": "未登录平台",
        "gui.dynamic_bgm.platform.status.waiting": "等待扫码中...",
        "gui.dynamic_bgm.platform.status.authorizing": "已扫码，等待手机端授权...",
        "gui.dynamic_bgm.platform.status.success": "登录成功！",
        "gui.dynamic_bgm.platform.status.expired": "二维码已过期，请重新登录！",
        "gui.dynamic_bgm.platform.status.error": "登录发生错误：",
        "gui.dynamic_bgm.rules.title": "环境触发规则",
        "gui.dynamic_bgm.rules.overworld": "主世界：",
        "gui.dynamic_bgm.rules.nether": "下界：",
        "gui.dynamic_bgm.rules.combat": "战斗：",
        "gui.dynamic_bgm.rules.boss": "首领战：",
        "gui.dynamic_bgm.rules.hint": "提示：点击音乐名称可切换绑定的本地曲目。",
        "gui.dynamic_bgm.settings.title": "模组设置",
        "gui.dynamic_bgm.settings.replace_vanilla": "替换原版音乐：",
        "gui.dynamic_bgm.settings.replace_desc1": "当播放流光音匣的音乐时，",
        "gui.dynamic_bgm.settings.replace_desc2": "将自动静音原版背景音乐。",
        "gui.dynamic_bgm.player.no_track": "未播放音乐",
        "gui.dynamic_bgm.player.volume": "音量",
        "gui.dynamic_bgm.player.play": "播放",
        "gui.dynamic_bgm.player.pause": "暂停",
        "gui.dynamic_bgm.generic.on": "开启",
        "gui.dynamic_bgm.generic.off": "关闭",
        "gui.dynamic_bgm.pause_menu_btn": "流光音匣",
        "gui.dynamic_bgm.local.select_all": "全选",
        "gui.dynamic_bgm.local.delete": "删除",
        "gui.dynamic_bgm.local.pin": "置顶",
        "gui.dynamic_bgm.local.select": "选择",
        "gui.dynamic_bgm.local.cancel": "取消",
        "gui.dynamic_bgm.platform.online_mode": "网络播放模式",
        "gui.dynamic_bgm.platform.no_results": "无搜索结果。",
        "gui.dynamic_bgm.platform.empty_list": "网络播放列表为空，请在上方搜索并添加歌曲",
        "gui.dynamic_bgm.server.empty_list": "服务器播放列表为空",
        "gui.dynamic_bgm.toast.added_to_online": "已添加到网络播放列表!",
        "gui.dynamic_bgm.toast.android_path": "检测到安卓系统, 请将音乐文件放入: ",
        "gui.dynamic_bgm.toast.upload_success": "上传完成!",
        "gui.dynamic_bgm.toast.file_not_found": "文件不存在!",
        "gui.dynamic_bgm.toast.network_error": "网络请求失败...",
        "gui.dynamic_bgm.settings.debug_log": "音频调试日志: "
    },
    "zh_tw": {
        "key.dynamic_bgm.open_menu": "打開音匣菜單",
        "key.categories.dynamic_bgm.main": "流光音匣",
        "gui.dynamic_bgm.title": "流光音匣 控制面板",
        "gui.dynamic_bgm.tab.local": "本地音樂",
        "gui.dynamic_bgm.tab.server": "伺服器內置",
        "gui.dynamic_bgm.tab.platform": "網路平台",
        "gui.dynamic_bgm.tab.rules": "環境觸發",
        "gui.dynamic_bgm.tab.settings": "模組設定",
        "gui.dynamic_bgm.local.title": "本地音樂庫",
        "gui.dynamic_bgm.local.no_music": "未找到本地音樂。",
        "gui.dynamic_bgm.local.instructions": "請將音訊檔案 (.mp3/.ogg) 放入：",
        "gui.dynamic_bgm.local.open_folder": "打開資料夾",
        "gui.dynamic_bgm.local.import": "匯入音樂",
        "gui.dynamic_bgm.local.download_sample": "下載範例",
        "gui.dynamic_bgm.local.refresh": "重新整理",
        "gui.dynamic_bgm.local.status": "狀態：",
        "gui.dynamic_bgm.local.status.ready": "就緒",
        "gui.dynamic_bgm.local.status.downloading": "正在下載範例音樂...",
        "gui.dynamic_bgm.local.status.success": "下載成功！",
        "gui.dynamic_bgm.local.status.fail": "下載失敗！",
        "gui.dynamic_bgm.server.title": "伺服器內置音樂",
        "gui.dynamic_bgm.server.status_connected": "狀態：已連接到伺服器",
        "gui.dynamic_bgm.server.priority": "伺服器播放列表優先控制。",
        "gui.dynamic_bgm.server.download_all": "下載全部",
        "gui.dynamic_bgm.server.sync": "同步曲庫",
        "gui.dynamic_bgm.platform.title": "網路平台播放",
        "gui.dynamic_bgm.platform.search_placeholder": "搜尋線上音樂...",
        "gui.dynamic_bgm.platform.search_btn": "搜尋",
        "gui.dynamic_bgm.platform.login": "掃碼登入",
        "gui.dynamic_bgm.platform.logout": "登出",
        "gui.dynamic_bgm.platform.logged_in": "已登入：",
        "gui.dynamic_bgm.platform.not_logged_in": "未登入",
        "gui.dynamic_bgm.platform.status.waiting": "等待掃碼中...",
        "gui.dynamic_bgm.platform.status.authorizing": "已掃碼，等待手機端授權...",
        "gui.dynamic_bgm.platform.status.success": "登入成功！",
        "gui.dynamic_bgm.platform.status.expired": "QR Code已過期，請重新登入！",
        "gui.dynamic_bgm.platform.status.error": "登入發生錯誤：",
        "gui.dynamic_bgm.rules.title": "環境觸發規則",
        "gui.dynamic_bgm.rules.overworld": "主世界：",
        "gui.dynamic_bgm.rules.nether": "下界：",
        "gui.dynamic_bgm.rules.combat": "戰鬥：",
        "gui.dynamic_bgm.rules.boss": "首領戰：",
        "gui.dynamic_bgm.rules.hint": "提示：點擊音樂名稱可切換綁定的本地曲目。",
        "gui.dynamic_bgm.settings.title": "模組設定",
        "gui.dynamic_bgm.settings.replace_vanilla": "替換原版音樂：",
        "gui.dynamic_bgm.settings.replace_desc1": "當播放流光音匣的音樂時，",
        "gui.dynamic_bgm.settings.replace_desc2": "將自動靜音原版背景音樂。",
        "gui.dynamic_bgm.player.no_track": "未播放音樂",
        "gui.dynamic_bgm.player.volume": "音量",
        "gui.dynamic_bgm.player.play": "播放",
        "gui.dynamic_bgm.player.pause": "暫停",
        "gui.dynamic_bgm.generic.on": "開啟",
        "gui.dynamic_bgm.generic.off": "關閉",
        "gui.dynamic_bgm.pause_menu_btn": "流光音匣",
        "gui.dynamic_bgm.local.select_all": "全選",
        "gui.dynamic_bgm.local.delete": "刪除",
        "gui.dynamic_bgm.local.pin": "置頂",
        "gui.dynamic_bgm.local.select": "選擇",
        "gui.dynamic_bgm.local.cancel": "取消",
        "gui.dynamic_bgm.platform.online_mode": "網路播放模式",
        "gui.dynamic_bgm.platform.no_results": "無搜尋結果。",
        "gui.dynamic_bgm.platform.empty_list": "網路播放列表為空，請在上方搜尋並加入歌曲",
        "gui.dynamic_bgm.server.empty_list": "伺服器播放列表為空",
        "gui.dynamic_bgm.toast.added_to_online": "已加入到網路播放列表!",
        "gui.dynamic_bgm.toast.android_path": "檢測到 Android 系統, 請將音樂檔案放入: ",
        "gui.dynamic_bgm.toast.upload_success": "上傳完成!",
        "gui.dynamic_bgm.toast.file_not_found": "檔案不存在!",
        "gui.dynamic_bgm.toast.network_error": "網路請求失敗...",
        "gui.dynamic_bgm.settings.debug_log": "音訊偵錯記錄: "
    },
    "ja_jp": {
        "key.dynamic_bgm.open_menu": "LuminaBox メニューを開く",
        "key.categories.dynamic_bgm.main": "LuminaBox",
        "gui.dynamic_bgm.title": "LuminaBox コントローラー",
        "gui.dynamic_bgm.tab.local": "ローカル音楽",
        "gui.dynamic_bgm.tab.server": "サーバー音楽",
        "gui.dynamic_bgm.tab.platform": "オンライン音楽",
        "gui.dynamic_bgm.tab.rules": "環境ルール",
        "gui.dynamic_bgm.tab.settings": "設定",
        "gui.dynamic_bgm.local.title": "ローカル音楽ライブラリ",
        "gui.dynamic_bgm.local.no_music": "ローカル音楽が見つかりません。",
        "gui.dynamic_bgm.local.instructions": "音声ファイル(.mp3/.ogg)を配置：",
        "gui.dynamic_bgm.local.open_folder": "フォルダを開く",
        "gui.dynamic_bgm.local.import": "音楽をインポート",
        "gui.dynamic_bgm.local.download_sample": "サンプルをダウンロード",
        "gui.dynamic_bgm.local.refresh": "更新",
        "gui.dynamic_bgm.local.status": "ステータス: ",
        "gui.dynamic_bgm.local.status.ready": "準備完了",
        "gui.dynamic_bgm.local.status.downloading": "サンプルをダウンロード中...",
        "gui.dynamic_bgm.local.status.success": "ダウンロード成功！",
        "gui.dynamic_bgm.local.status.fail": "ダウンロード失敗！",
        "gui.dynamic_bgm.server.title": "サーバー同期音楽",
        "gui.dynamic_bgm.server.status_connected": "ステータス: サーバーに接続済み",
        "gui.dynamic_bgm.server.priority": "サーバーのプレイリストが優先されます。",
        "gui.dynamic_bgm.server.download_all": "すべてダウンロード",
        "gui.dynamic_bgm.server.sync": "リストを同期",
        "gui.dynamic_bgm.platform.title": "オンラインプラットフォーム",
        "gui.dynamic_bgm.platform.search_placeholder": "オンライン音楽を検索...",
        "gui.dynamic_bgm.platform.search_btn": "検索",
        "gui.dynamic_bgm.platform.login": "QRログイン",
        "gui.dynamic_bgm.platform.logout": "ログアウト",
        "gui.dynamic_bgm.platform.logged_in": "ログイン済み: ",
        "gui.dynamic_bgm.platform.not_logged_in": "未ログイン",
        "gui.dynamic_bgm.platform.status.waiting": "スキャンを待機中...",
        "gui.dynamic_bgm.platform.status.authorizing": "スキャン完了！認証中...",
        "gui.dynamic_bgm.platform.status.success": "ログイン成功！",
        "gui.dynamic_bgm.platform.status.expired": "QRコードの有効期限が切れました",
        "gui.dynamic_bgm.platform.status.error": "ログインエラー: ",
        "gui.dynamic_bgm.rules.title": "環境音楽ルール",
        "gui.dynamic_bgm.rules.overworld": "オーバーワールド: ",
        "gui.dynamic_bgm.rules.nether": "ネザー: ",
        "gui.dynamic_bgm.rules.combat": "戦闘: ",
        "gui.dynamic_bgm.rules.boss": "ボス: ",
        "gui.dynamic_bgm.rules.hint": "ヒント: 音楽名をクリックして切り替え。",
        "gui.dynamic_bgm.settings.title": "Mod設定",
        "gui.dynamic_bgm.settings.replace_vanilla": "バニラ音楽を置換: ",
        "gui.dynamic_bgm.settings.replace_desc1": "LuminaBoxの音楽の再生中は",
        "gui.dynamic_bgm.settings.replace_desc2": "バニラのBGMをミュートします。",
        "gui.dynamic_bgm.player.no_track": "再生していません",
        "gui.dynamic_bgm.player.volume": "音量",
        "gui.dynamic_bgm.player.play": "再生",
        "gui.dynamic_bgm.player.pause": "一時停止",
        "gui.dynamic_bgm.generic.on": "オン",
        "gui.dynamic_bgm.generic.off": "オフ",
        "gui.dynamic_bgm.pause_menu_btn": "LuminaBox",
        "gui.dynamic_bgm.local.select_all": "すべて選択",
        "gui.dynamic_bgm.local.delete": "削除",
        "gui.dynamic_bgm.local.pin": "トップに固定",
        "gui.dynamic_bgm.local.select": "選択",
        "gui.dynamic_bgm.local.cancel": "キャンセル",
        "gui.dynamic_bgm.platform.online_mode": "オンラインモード",
        "gui.dynamic_bgm.platform.no_results": "検索結果がありません。",
        "gui.dynamic_bgm.platform.empty_list": "プレイリストが空です。",
        "gui.dynamic_bgm.server.empty_list": "サーバープレイリストが空です。",
        "gui.dynamic_bgm.toast.added_to_online": "オンラインプレイリストに追加しました！",
        "gui.dynamic_bgm.toast.android_path": "Androidを検出、ここに配置: ",
        "gui.dynamic_bgm.toast.upload_success": "アップロード完了！",
        "gui.dynamic_bgm.toast.file_not_found": "ファイルが見つかりません！",
        "gui.dynamic_bgm.toast.network_error": "ネットワークリクエスト失敗...",
        "gui.dynamic_bgm.settings.debug_log": "オーディオデバッグログ: "
    },
    "ko_kr": {
        "key.dynamic_bgm.open_menu": "LuminaBox 메뉴 열기",
        "key.categories.dynamic_bgm.main": "LuminaBox",
        "gui.dynamic_bgm.title": "LuminaBox 컨트롤러",
        "gui.dynamic_bgm.tab.local": "로컬 음악",
        "gui.dynamic_bgm.tab.server": "서버 음악",
        "gui.dynamic_bgm.tab.platform": "온라인 플랫폼",
        "gui.dynamic_bgm.tab.rules": "환경 규칙",
        "gui.dynamic_bgm.tab.settings": "설정",
        "gui.dynamic_bgm.local.title": "로컬 음악 라이브러리",
        "gui.dynamic_bgm.local.no_music": "로컬 음악을 찾을 수 없습니다.",
        "gui.dynamic_bgm.local.instructions": "오디오 파일(.mp3/.ogg) 경로:",
        "gui.dynamic_bgm.local.open_folder": "폴더 열기",
        "gui.dynamic_bgm.local.import": "음악 가져오기",
        "gui.dynamic_bgm.local.download_sample": "샘플 다운로드",
        "gui.dynamic_bgm.local.refresh": "새로고침",
        "gui.dynamic_bgm.local.status": "상태: ",
        "gui.dynamic_bgm.local.status.ready": "준비됨",
        "gui.dynamic_bgm.local.status.downloading": "샘플 다운로드 중...",
        "gui.dynamic_bgm.local.status.success": "다운로드 성공!",
        "gui.dynamic_bgm.local.status.fail": "다운로드 실패!",
        "gui.dynamic_bgm.server.title": "서버 동기화 음악",
        "gui.dynamic_bgm.server.status_connected": "상태: 서버에 연결됨",
        "gui.dynamic_bgm.server.priority": "서버 재생 목록이 우선 적용됩니다.",
        "gui.dynamic_bgm.server.download_all": "모두 다운로드",
        "gui.dynamic_bgm.server.sync": "목록 동기화",
        "gui.dynamic_bgm.platform.title": "온라인 플랫폼 재생",
        "gui.dynamic_bgm.platform.search_placeholder": "온라인 음악 검색...",
        "gui.dynamic_bgm.platform.search_btn": "검색",
        "gui.dynamic_bgm.platform.login": "QR 로그인",
        "gui.dynamic_bgm.platform.logout": "로그아웃",
        "gui.dynamic_bgm.platform.logged_in": "로그인됨: ",
        "gui.dynamic_bgm.platform.not_logged_in": "로그인되지 않음",
        "gui.dynamic_bgm.platform.status.waiting": "스캔 대기 중...",
        "gui.dynamic_bgm.platform.status.authorizing": "스캔 완료! 인증 중...",
        "gui.dynamic_bgm.platform.status.success": "로그인 성공!",
        "gui.dynamic_bgm.platform.status.expired": "QR 코드가 만료되었습니다!",
        "gui.dynamic_bgm.platform.status.error": "로그인 오류: ",
        "gui.dynamic_bgm.rules.title": "환경 음악 규칙",
        "gui.dynamic_bgm.rules.overworld": "오버월드: ",
        "gui.dynamic_bgm.rules.nether": "네더: ",
        "gui.dynamic_bgm.rules.combat": "전투: ",
        "gui.dynamic_bgm.rules.boss": "보스: ",
        "gui.dynamic_bgm.rules.hint": "팁: 음악 이름을 클릭하여 로컬 트랙을 전환합니다.",
        "gui.dynamic_bgm.settings.title": "모드 설정",
        "gui.dynamic_bgm.settings.replace_vanilla": "바닐라 음악 교체: ",
        "gui.dynamic_bgm.settings.replace_desc1": "LuminaBox 음악이 재생될 때",
        "gui.dynamic_bgm.settings.replace_desc2": "바닐라 BGM을 음소거합니다.",
        "gui.dynamic_bgm.player.no_track": "재생 중인 음악 없음",
        "gui.dynamic_bgm.player.volume": "음량",
        "gui.dynamic_bgm.player.play": "재생",
        "gui.dynamic_bgm.player.pause": "일시정지",
        "gui.dynamic_bgm.generic.on": "켜짐",
        "gui.dynamic_bgm.generic.off": "꺼짐",
        "gui.dynamic_bgm.pause_menu_btn": "LuminaBox",
        "gui.dynamic_bgm.local.select_all": "모두 선택",
        "gui.dynamic_bgm.local.delete": "삭제",
        "gui.dynamic_bgm.local.pin": "맨 위에 고정",
        "gui.dynamic_bgm.local.select": "선택",
        "gui.dynamic_bgm.local.cancel": "취소",
        "gui.dynamic_bgm.platform.online_mode": "온라인 모드",
        "gui.dynamic_bgm.platform.no_results": "검색 결과가 없습니다.",
        "gui.dynamic_bgm.platform.empty_list": "온라인 재생 목록이 비어 있습니다.",
        "gui.dynamic_bgm.server.empty_list": "서버 재생 목록이 비어 있습니다.",
        "gui.dynamic_bgm.toast.added_to_online": "온라인 재생 목록에 추가되었습니다!",
        "gui.dynamic_bgm.toast.android_path": "Android 감지됨, 음악 폴더: ",
        "gui.dynamic_bgm.toast.upload_success": "업로드 완료!",
        "gui.dynamic_bgm.toast.file_not_found": "파일을 찾을 수 없습니다!",
        "gui.dynamic_bgm.toast.network_error": "네트워크 요청 실패...",
        "gui.dynamic_bgm.settings.debug_log": "오디오 디버그 로그: "
    },
    "fr_fr": {
        "key.dynamic_bgm.open_menu": "Ouvrir le menu LuminaBox",
        "key.categories.dynamic_bgm.main": "LuminaBox",
        "gui.dynamic_bgm.title": "Contrôleur LuminaBox",
        "gui.dynamic_bgm.tab.local": "Musique Locale",
        "gui.dynamic_bgm.tab.server": "Musique du Serveur",
        "gui.dynamic_bgm.tab.platform": "Plateforme en Ligne",
        "gui.dynamic_bgm.tab.rules": "Règles d'Ambiance",
        "gui.dynamic_bgm.tab.settings": "Paramètres",
        "gui.dynamic_bgm.local.title": "Bibliothèque de Musique Locale",
        "gui.dynamic_bgm.local.no_music": "Aucune musique locale trouvée.",
        "gui.dynamic_bgm.local.instructions": "Placez les fichiers (.mp3/.ogg) dans :",
        "gui.dynamic_bgm.local.open_folder": "Ouvrir le Dossier",
        "gui.dynamic_bgm.local.import": "Importer de la Musique",
        "gui.dynamic_bgm.local.download_sample": "Télécharger un Échantillon",
        "gui.dynamic_bgm.local.refresh": "Rafraîchir",
        "gui.dynamic_bgm.local.status": "Statut : ",
        "gui.dynamic_bgm.local.status.ready": "Prêt",
        "gui.dynamic_bgm.local.status.downloading": "Téléchargement...",
        "gui.dynamic_bgm.local.status.success": "Téléchargement réussi !",
        "gui.dynamic_bgm.local.status.fail": "Échec du téléchargement !",
        "gui.dynamic_bgm.server.title": "Musique Sync du Serveur",
        "gui.dynamic_bgm.server.status_connected": "Statut : Connecté au Serveur",
        "gui.dynamic_bgm.server.priority": "La liste de lecture du serveur est prioritaire.",
        "gui.dynamic_bgm.server.download_all": "Tout Télécharger",
        "gui.dynamic_bgm.server.sync": "Sync la Liste",
        "gui.dynamic_bgm.platform.title": "Plateforme en Ligne",
        "gui.dynamic_bgm.platform.search_placeholder": "Rechercher de la musique...",
        "gui.dynamic_bgm.platform.search_btn": "Rechercher",
        "gui.dynamic_bgm.platform.login": "Connexion QR",
        "gui.dynamic_bgm.platform.logout": "Déconnexion",
        "gui.dynamic_bgm.platform.logged_in": "Connecté : ",
        "gui.dynamic_bgm.platform.not_logged_in": "Non connecté",
        "gui.dynamic_bgm.platform.status.waiting": "En attente de scan...",
        "gui.dynamic_bgm.platform.status.authorizing": "Scanné ! Autorisation...",
        "gui.dynamic_bgm.platform.status.success": "Connexion réussie !",
        "gui.dynamic_bgm.platform.status.expired": "Code QR expiré !",
        "gui.dynamic_bgm.platform.status.error": "Erreur de connexion : ",
        "gui.dynamic_bgm.rules.title": "Règles d'Ambiance",
        "gui.dynamic_bgm.rules.overworld": "Overworld : ",
        "gui.dynamic_bgm.rules.nether": "Nether : ",
        "gui.dynamic_bgm.rules.combat": "Combat : ",
        "gui.dynamic_bgm.rules.boss": "Boss : ",
        "gui.dynamic_bgm.rules.hint": "Astuce : Cliquez pour changer de piste.",
        "gui.dynamic_bgm.settings.title": "Configurations",
        "gui.dynamic_bgm.settings.replace_vanilla": "Remplacer la Musique Vanilla : ",
        "gui.dynamic_bgm.settings.replace_desc1": "Remplace la musique de fond vanilla",
        "gui.dynamic_bgm.settings.replace_desc2": "quand LuminaBox joue de la musique.",
        "gui.dynamic_bgm.player.no_track": "Aucune musique en cours",
        "gui.dynamic_bgm.player.volume": "Vol",
        "gui.dynamic_bgm.player.play": "Jouer",
        "gui.dynamic_bgm.player.pause": "Pause",
        "gui.dynamic_bgm.generic.on": "ON",
        "gui.dynamic_bgm.generic.off": "OFF",
        "gui.dynamic_bgm.pause_menu_btn": "LuminaBox",
        "gui.dynamic_bgm.local.select_all": "Tout Sélectionner",
        "gui.dynamic_bgm.local.delete": "Supprimer",
        "gui.dynamic_bgm.local.pin": "Épingler",
        "gui.dynamic_bgm.local.select": "Sélectionner",
        "gui.dynamic_bgm.local.cancel": "Annuler",
        "gui.dynamic_bgm.platform.online_mode": "Mode en Ligne",
        "gui.dynamic_bgm.platform.no_results": "Aucun résultat trouvé.",
        "gui.dynamic_bgm.platform.empty_list": "Liste en ligne vide.",
        "gui.dynamic_bgm.server.empty_list": "La liste de lecture du serveur est vide.",
        "gui.dynamic_bgm.toast.added_to_online": "Ajouté à la liste en ligne !",
        "gui.dynamic_bgm.toast.android_path": "Android détecté, dossier: ",
        "gui.dynamic_bgm.toast.upload_success": "Téléversement terminé !",
        "gui.dynamic_bgm.toast.file_not_found": "Fichier introuvable !",
        "gui.dynamic_bgm.toast.network_error": "Échec de la requête réseau...",
        "gui.dynamic_bgm.settings.debug_log": "Journal de débogage Audio : "
    },
    "es_es": {
        "key.dynamic_bgm.open_menu": "Abrir Menú LuminaBox",
        "key.categories.dynamic_bgm.main": "LuminaBox",
        "gui.dynamic_bgm.title": "Controlador LuminaBox",
        "gui.dynamic_bgm.tab.local": "Música Local",
        "gui.dynamic_bgm.tab.server": "Música del Servidor",
        "gui.dynamic_bgm.tab.platform": "Plataforma en Línea",
        "gui.dynamic_bgm.tab.rules": "Reglas de Ambiente",
        "gui.dynamic_bgm.tab.settings": "Ajustes",
        "gui.dynamic_bgm.local.title": "Biblioteca de Música Local",
        "gui.dynamic_bgm.local.no_music": "No se encontró música local.",
        "gui.dynamic_bgm.local.instructions": "Coloque archivos (.mp3/.ogg) en:",
        "gui.dynamic_bgm.local.open_folder": "Abrir Carpeta",
        "gui.dynamic_bgm.local.import": "Importar Música",
        "gui.dynamic_bgm.local.download_sample": "Descargar Muestra",
        "gui.dynamic_bgm.local.refresh": "Actualizar Lista",
        "gui.dynamic_bgm.local.status": "Estado: ",
        "gui.dynamic_bgm.local.status.ready": "Listo",
        "gui.dynamic_bgm.local.status.downloading": "Descargando...",
        "gui.dynamic_bgm.local.status.success": "¡Descarga exitosa!",
        "gui.dynamic_bgm.local.status.fail": "¡Descarga fallida!",
        "gui.dynamic_bgm.server.title": "Música Sincronizada",
        "gui.dynamic_bgm.server.status_connected": "Estado: Conectado al Servidor",
        "gui.dynamic_bgm.server.priority": "La lista del servidor tiene prioridad.",
        "gui.dynamic_bgm.server.download_all": "Descargar Todo",
        "gui.dynamic_bgm.server.sync": "Sincronizar",
        "gui.dynamic_bgm.platform.title": "Plataforma en Línea",
        "gui.dynamic_bgm.platform.search_placeholder": "Buscar música en línea...",
        "gui.dynamic_bgm.platform.search_btn": "Buscar",
        "gui.dynamic_bgm.platform.login": "Iniciar Sesión (QR)",
        "gui.dynamic_bgm.platform.logout": "Cerrar Sesión",
        "gui.dynamic_bgm.platform.logged_in": "Sesión iniciada: ",
        "gui.dynamic_bgm.platform.not_logged_in": "No iniciada",
        "gui.dynamic_bgm.platform.status.waiting": "Esperando escaneo...",
        "gui.dynamic_bgm.platform.status.authorizing": "¡Escaneado! Autorizando...",
        "gui.dynamic_bgm.platform.status.success": "¡Sesión iniciada!",
        "gui.dynamic_bgm.platform.status.expired": "¡El código QR expiró!",
        "gui.dynamic_bgm.platform.status.error": "Error de inicio de sesión: ",
        "gui.dynamic_bgm.rules.title": "Reglas de Ambiente",
        "gui.dynamic_bgm.rules.overworld": "Mundo Normal: ",
        "gui.dynamic_bgm.rules.nether": "Nether: ",
        "gui.dynamic_bgm.rules.combat": "Combate: ",
        "gui.dynamic_bgm.rules.boss": "Jefe: ",
        "gui.dynamic_bgm.rules.hint": "Consejo: Haz clic en la pista para cambiarla.",
        "gui.dynamic_bgm.settings.title": "Configuraciones",
        "gui.dynamic_bgm.settings.replace_vanilla": "Reemplazar Música Vanilla: ",
        "gui.dynamic_bgm.settings.replace_desc1": "Silencia la música de fondo vanilla",
        "gui.dynamic_bgm.settings.replace_desc2": "cuando LuminaBox reproduce música.",
        "gui.dynamic_bgm.player.no_track": "Sin música en reproducción",
        "gui.dynamic_bgm.player.volume": "Vol",
        "gui.dynamic_bgm.player.play": "Reproducir",
        "gui.dynamic_bgm.player.pause": "Pausa",
        "gui.dynamic_bgm.generic.on": "ON",
        "gui.dynamic_bgm.generic.off": "OFF",
        "gui.dynamic_bgm.pause_menu_btn": "LuminaBox",
        "gui.dynamic_bgm.local.select_all": "Seleccionar Todo",
        "gui.dynamic_bgm.local.delete": "Eliminar",
        "gui.dynamic_bgm.local.pin": "Fijar Arriba",
        "gui.dynamic_bgm.local.select": "Seleccionar",
        "gui.dynamic_bgm.local.cancel": "Cancelar",
        "gui.dynamic_bgm.platform.online_mode": "Modo en Línea",
        "gui.dynamic_bgm.platform.no_results": "No se encontraron resultados.",
        "gui.dynamic_bgm.platform.empty_list": "Lista en línea vacía.",
        "gui.dynamic_bgm.server.empty_list": "La lista del servidor está vacía.",
        "gui.dynamic_bgm.toast.added_to_online": "¡Añadido a la lista en línea!",
        "gui.dynamic_bgm.toast.android_path": "Android detectado, carpeta: ",
        "gui.dynamic_bgm.toast.upload_success": "¡Carga completa!",
        "gui.dynamic_bgm.toast.file_not_found": "¡Archivo no encontrado!",
        "gui.dynamic_bgm.toast.network_error": "Error de solicitud de red...",
        "gui.dynamic_bgm.settings.debug_log": "Registro de depuración: "
    },
    "ar_sa": {
        "key.dynamic_bgm.open_menu": "فتح قائمة LuminaBox",
        "key.categories.dynamic_bgm.main": "LuminaBox",
        "gui.dynamic_bgm.title": "وحدة تحكم LuminaBox",
        "gui.dynamic_bgm.tab.local": "الموسيقى المحلية",
        "gui.dynamic_bgm.tab.server": "موسيقى السيرفر",
        "gui.dynamic_bgm.tab.platform": "موسيقى المنصات",
        "gui.dynamic_bgm.tab.rules": "قواعد البيئة",
        "gui.dynamic_bgm.tab.settings": "الإعدادات",
        "gui.dynamic_bgm.local.title": "مكتبة الموسيقى المحلية",
        "gui.dynamic_bgm.local.no_music": "لم يتم العثور على موسيقى.",
        "gui.dynamic_bgm.local.instructions": "ضع ملفات (.mp3/.ogg) في:",
        "gui.dynamic_bgm.local.open_folder": "فتح المجلد",
        "gui.dynamic_bgm.local.import": "استيراد الموسيقى",
        "gui.dynamic_bgm.local.download_sample": "تحميل عينة",
        "gui.dynamic_bgm.local.refresh": "تحديث القائمة",
        "gui.dynamic_bgm.local.status": "الحالة: ",
        "gui.dynamic_bgm.local.status.ready": "جاهز",
        "gui.dynamic_bgm.local.status.downloading": "جارٍ التحميل...",
        "gui.dynamic_bgm.local.status.success": "تم التحميل بنجاح!",
        "gui.dynamic_bgm.local.status.fail": "فشل التحميل!",
        "gui.dynamic_bgm.server.title": "موسيقى السيرفر المتزامنة",
        "gui.dynamic_bgm.server.status_connected": "متصل بالسيرفر",
        "gui.dynamic_bgm.server.priority": "قائمة السيرفر لها الأولوية.",
        "gui.dynamic_bgm.server.download_all": "تحميل الكل",
        "gui.dynamic_bgm.server.sync": "مزامنة",
        "gui.dynamic_bgm.platform.title": "المنصة عبر الإنترنت",
        "gui.dynamic_bgm.platform.search_placeholder": "ابحث عن الموسيقى...",
        "gui.dynamic_bgm.platform.search_btn": "بحث",
        "gui.dynamic_bgm.platform.login": "تسجيل دخول QR",
        "gui.dynamic_bgm.platform.logout": "تسجيل خروج",
        "gui.dynamic_bgm.platform.logged_in": "تم تسجيل الدخول: ",
        "gui.dynamic_bgm.platform.not_logged_in": "غير مسجل",
        "gui.dynamic_bgm.platform.status.waiting": "في انتظار المسح...",
        "gui.dynamic_bgm.platform.status.authorizing": "تم المسح! جارٍ المصادقة...",
        "gui.dynamic_bgm.platform.status.success": "تم تسجيل الدخول!",
        "gui.dynamic_bgm.platform.status.expired": "انتهت صلاحية الرمز!",
        "gui.dynamic_bgm.platform.status.error": "خطأ: ",
        "gui.dynamic_bgm.rules.title": "قواعد البيئة",
        "gui.dynamic_bgm.rules.overworld": "العالم العادي: ",
        "gui.dynamic_bgm.rules.nether": "النيذر: ",
        "gui.dynamic_bgm.rules.combat": "القتال: ",
        "gui.dynamic_bgm.rules.boss": "الزعيم: ",
        "gui.dynamic_bgm.rules.hint": "تلميح: انقر للتبديل.",
        "gui.dynamic_bgm.settings.title": "الإعدادات",
        "gui.dynamic_bgm.settings.replace_vanilla": "استبدال الموسيقى الأصلية: ",
        "gui.dynamic_bgm.settings.replace_desc1": "كتم الموسيقى الأصلية للعبة",
        "gui.dynamic_bgm.settings.replace_desc2": "عندما تعمل LuminaBox.",
        "gui.dynamic_bgm.player.no_track": "لا يوجد موسيقى",
        "gui.dynamic_bgm.player.volume": "الصوت",
        "gui.dynamic_bgm.player.play": "تشغيل",
        "gui.dynamic_bgm.player.pause": "إيقاف",
        "gui.dynamic_bgm.generic.on": "تشغيل",
        "gui.dynamic_bgm.generic.off": "إيقاف",
        "gui.dynamic_bgm.pause_menu_btn": "LuminaBox",
        "gui.dynamic_bgm.local.select_all": "تحديد الكل",
        "gui.dynamic_bgm.local.delete": "حذف",
        "gui.dynamic_bgm.local.pin": "تثبيت",
        "gui.dynamic_bgm.local.select": "تحديد",
        "gui.dynamic_bgm.local.cancel": "إلغاء",
        "gui.dynamic_bgm.platform.online_mode": "الوضع عبر الإنترنت",
        "gui.dynamic_bgm.platform.no_results": "لم يتم العثور على نتائج.",
        "gui.dynamic_bgm.platform.empty_list": "قائمة الإنترنت فارغة.",
        "gui.dynamic_bgm.server.empty_list": "قائمة السيرفر فارغة.",
        "gui.dynamic_bgm.toast.added_to_online": "تمت الإضافة للقائمة!",
        "gui.dynamic_bgm.toast.android_path": "مسار أندرويد: ",
        "gui.dynamic_bgm.toast.upload_success": "تم الرفع بنجاح!",
        "gui.dynamic_bgm.toast.file_not_found": "الملف غير موجود!",
        "gui.dynamic_bgm.toast.network_error": "فشل الاتصال بالشبكة...",
        "gui.dynamic_bgm.settings.debug_log": "سجل التصحيح: "
    },
    "pt_br": {
        "key.dynamic_bgm.open_menu": "Abrir Menu LuminaBox",
        "key.categories.dynamic_bgm.main": "LuminaBox",
        "gui.dynamic_bgm.title": "Controlador LuminaBox",
        "gui.dynamic_bgm.tab.local": "Música Local",
        "gui.dynamic_bgm.tab.server": "Música do Servidor",
        "gui.dynamic_bgm.tab.platform": "Plataforma Online",
        "gui.dynamic_bgm.tab.rules": "Regras de Ambiente",
        "gui.dynamic_bgm.tab.settings": "Configurações",
        "gui.dynamic_bgm.local.title": "Biblioteca de Música Local",
        "gui.dynamic_bgm.local.no_music": "Nenhuma música local encontrada.",
        "gui.dynamic_bgm.local.instructions": "Coloque arquivos (.mp3/.ogg) em:",
        "gui.dynamic_bgm.local.open_folder": "Abrir Pasta",
        "gui.dynamic_bgm.local.import": "Importar Música",
        "gui.dynamic_bgm.local.download_sample": "Baixar Amostra",
        "gui.dynamic_bgm.local.refresh": "Atualizar Lista",
        "gui.dynamic_bgm.local.status": "Status: ",
        "gui.dynamic_bgm.local.status.ready": "Pronto",
        "gui.dynamic_bgm.local.status.downloading": "Baixando...",
        "gui.dynamic_bgm.local.status.success": "Download concluído!",
        "gui.dynamic_bgm.local.status.fail": "Falha no download!",
        "gui.dynamic_bgm.server.title": "Música Sincronizada",
        "gui.dynamic_bgm.server.status_connected": "Status: Conectado ao Servidor",
        "gui.dynamic_bgm.server.priority": "A lista do servidor tem prioridade.",
        "gui.dynamic_bgm.server.download_all": "Baixar Tudo",
        "gui.dynamic_bgm.server.sync": "Sincronizar",
        "gui.dynamic_bgm.platform.title": "Plataforma Online",
        "gui.dynamic_bgm.platform.search_placeholder": "Pesquisar música online...",
        "gui.dynamic_bgm.platform.search_btn": "Pesquisar",
        "gui.dynamic_bgm.platform.login": "Login QR",
        "gui.dynamic_bgm.platform.logout": "Sair",
        "gui.dynamic_bgm.platform.logged_in": "Logado: ",
        "gui.dynamic_bgm.platform.not_logged_in": "Não logado",
        "gui.dynamic_bgm.platform.status.waiting": "Aguardando verificação...",
        "gui.dynamic_bgm.platform.status.authorizing": "Verificado! Autorizando...",
        "gui.dynamic_bgm.platform.status.success": "Login concluído!",
        "gui.dynamic_bgm.platform.status.expired": "Código QR expirou!",
        "gui.dynamic_bgm.platform.status.error": "Erro de login: ",
        "gui.dynamic_bgm.rules.title": "Regras de Ambiente",
        "gui.dynamic_bgm.rules.overworld": "Mundo Normal: ",
        "gui.dynamic_bgm.rules.nether": "Nether: ",
        "gui.dynamic_bgm.rules.combat": "Combate: ",
        "gui.dynamic_bgm.rules.boss": "Chefe: ",
        "gui.dynamic_bgm.rules.hint": "Dica: Clique para alterar a faixa.",
        "gui.dynamic_bgm.settings.title": "Configurações",
        "gui.dynamic_bgm.settings.replace_vanilla": "Substituir Música Vanilla: ",
        "gui.dynamic_bgm.settings.replace_desc1": "Silencia a música de fundo vanilla",
        "gui.dynamic_bgm.settings.replace_desc2": "quando a LuminaBox toca música.",
        "gui.dynamic_bgm.player.no_track": "Nenhuma música tocando",
        "gui.dynamic_bgm.player.volume": "Vol",
        "gui.dynamic_bgm.player.play": "Tocar",
        "gui.dynamic_bgm.player.pause": "Pausar",
        "gui.dynamic_bgm.generic.on": "LIGADO",
        "gui.dynamic_bgm.generic.off": "DESLIGADO",
        "gui.dynamic_bgm.pause_menu_btn": "LuminaBox",
        "gui.dynamic_bgm.local.select_all": "Selecionar Tudo",
        "gui.dynamic_bgm.local.delete": "Excluir",
        "gui.dynamic_bgm.local.pin": "Fixar no Topo",
        "gui.dynamic_bgm.local.select": "Selecionar",
        "gui.dynamic_bgm.local.cancel": "Cancelar",
        "gui.dynamic_bgm.platform.online_mode": "Modo Online",
        "gui.dynamic_bgm.platform.no_results": "Nenhum resultado.",
        "gui.dynamic_bgm.platform.empty_list": "Lista online vazia.",
        "gui.dynamic_bgm.server.empty_list": "Lista do servidor está vazia.",
        "gui.dynamic_bgm.toast.added_to_online": "Adicionado à lista online!",
        "gui.dynamic_bgm.toast.android_path": "Android detectado, pasta: ",
        "gui.dynamic_bgm.toast.upload_success": "Envio concluído!",
        "gui.dynamic_bgm.toast.file_not_found": "Arquivo não encontrado!",
        "gui.dynamic_bgm.toast.network_error": "Falha na solicitação de rede...",
        "gui.dynamic_bgm.settings.debug_log": "Registro de depuração: "
    }
}

for lang_code, lang_json in langs_data.items():
    file_path = os.path.join(lang_dir, f"{lang_code}.json")
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(lang_json, f, ensure_ascii=False, indent=2)

print("SUCCESS: Refactored and wrote all 9 language files.")
